<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>Rebar-error</AssemblyName>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath>..\..\release</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Tekla.Structures">
      <HintPath>$(TeklaDir)\Tekla.Structures.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Tekla.Structures.Model">
      <HintPath>$(TeklaDir)\Tekla.Structures.Model.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
